INSERT INTO companies (name, website, address, source)
VALUES ('TechCorp', 'http://techcorp.com', '123 Tech Street', 'API_1'),
       ('TECHCORP', 'http://techcorp.com', '123 Tech Street', 'SCRAPER_2'),
       ('TechCorp', 'http://techcorp.com', '123 Tech Street', 'MANUAL'),
       ('Innovate', 'http://innovate.com', '456 Innovation Rd', 'API_1'),
       ('INNOVATE', 'http://innovate.com', '456 Innovation Rd', 'SCRAPER_2'),
       ('FutureSoft', 'http://futuresoft.io', '789 Future Blvd', 'API_1'),
       ('FUTURESOFT', 'http://futuresoft.io', '789 Future Blvd', 'SCRAPER_2'),
       ('GreenTech', 'http://greentech.org', '101 Green Way', 'MANUAL'),
       ('EcoPower', 'http://ecopower.net', '202 Eco Lane', 'API_1'),
       ('NextGenAI', 'http://nextgenai.com', '303 AI Drive', 'MANUAL'),
       ('CyberDyn', 'http://cyberdyn.com', '404 Cyber Street', 'SCRAPER_2'),
       ('CLOUDSYNC', 'http://cloudsync.io', '505 Cloud Blvd', 'SCRAPER_2'),
       ('NeuralNet', 'http://neuralnet.ai', '606 Neural Ave', 'API_1'),
       ('QuantumTech', 'http://quantumtech.com', '707 Quantum Rd', 'API_1'),
       ('QUANTUMTECH', 'http://quantumtech.com', '707 Quantum Rd', 'SCRAPER_2'),
       ('HyperLoop', 'http://hyperloop.io', '808 Speedway', 'MANUAL'),
       ('SolarGrid', 'http://solargrid.org', '909 Solar Street', 'SCRAPER_2'),
       ('SOLARGRID', 'http://solargrid.org', '909 Solar Street', 'API_1'),
       ('NanoTech', 'http://nanotechlabs.com', '1010 Nano Lane', 'MANUAL'),
       ('NANOTECH', 'http://nanotechlabs.com', '1010 Nano Lane', 'API_1'),
       ('MedTech', 'http://medtech.co', '1111 MedPark', 'SCRAPER_2'),
       ('BIOGEN', 'http://biogen.io', '1212 Bio Ave', 'SCRAPER_2'),
       ('SmartGrid', 'http://smartgrid.tech', '1313 Power Way', 'API_1'),
       ('AutoAI', 'http://autoai.com', '1414 Drive Rd', 'SCRAPER_2'),
       ('FutureEnergy', 'http://futureenergy.net', '1515 Renewable St', 'API_1'),
       ('DeepLearning', 'http://deeplearning.ai', '1616 ML Lane', 'MANUAL'),
       ('Singularity', 'http://singularity.io', '1717 AI Blvd', 'API_1'),
       ('NeuroTech', 'http://neurotech.com', '1818 Brain St', 'MANUAL'),
       ('SolarFuture', 'http://solarfuture.org', '1919 Sun Drive', 'SCRAPER_2'),
       ('AlphaTech', 'http://alphatech.com', '2020 Alpha Street', 'API_1'),
       ('ALPHATECH', 'http://alphatech.com', '2020 Alpha Street', 'SCRAPER_2'),
       ('AlphaTech', 'http://alphatech.com', '2020 Alpha Street', 'MANUAL'),
       ('GlobalNet', 'http://globalnet.io', '2121 Global Avenue', 'API_1'),
       ('GLOBALNET', 'http://globalnet.io', '2121 Global Avenue', 'SCRAPER_2'),
       ('GlobalNet', 'http://globalnet.io', '2121 Global Avenue', 'MANUAL');